Repository 89luca89/terrible, pull requests merged in 2020-10, with the labels that each got.

#40 39 add ansible lint
  .github/workflows/ansible-lint.yml
  README.md
  roles/terrible/tasks/deploy_vm.yml
  roles/terrible/tasks/network/network_FreeBSD_setup.yml
  roles/terrible/tasks/network/network_RedHat_setup.yml
  roles/terrible/tasks/network/network_Suse_setup.yml
Labels: enhancement

#43 42 fix ci errors
  roles/terrible/tasks/deploy_vm.yml
  roles/terrible/tasks/network/network_Debian_setup.yml
  roles/terrible/tasks/network/network_FreeBSD_setup.yml
  roles/terrible/tasks/network/network_RedHat_setup.yml
  roles/terrible/tasks/network/network_Suse_setup.yml
  roles/terrible/tasks/post_deploy.yml
  roles/terrible/tasks/setup_vars.yml
  roles/terrible/tasks/state_restore.yml
  roles/terrible/tasks/storage/disk_Debian_setup.yml
  roles/terrible/tasks/storage/disk_FreeBSD_setup.yml
  roles/terrible/tasks/storage/disk_RedHat_setup.yml
  roles/terrible/tasks/storage/disk_Suse_setup.yml
Labels: bug

#47 Created Table of Contents and fixed some description
  README.md
Labels: documentation
